### ISSUE TITLE
fixing the stupid site

### ISSUE THREAD

**Issue by ConnorAhern** [DigitalTeal/digitalteal-website#4]
1. - [x] the theme is inconsistent; index, subtoemail, and team have the right theme
2. - [x] create /contact
2. - [x] the cards on /team need to appear in order and in their container, not on random parts of the page
3. - [x] the code integrity bot detected 200 issues i tried to fix it and added another 41 onto it 
4. - [x] recreate 404 page 
5. - [ ] add other error pages

**Comment by ChickenOnYT** [comment]
@irhrhd there ya go

**Comment by irhrhd** [comment]
Thanks Lol

**Comment by ChickenOnYT** [comment]
np

**Comment by irhrhd** [comment]
Well S*** this is gonna be awhile

**Comment by ChickenOnYT** [comment]
mk

**Comment by irhrhd** [comment]
Well I just fixed more than half the errors

**Comment by ChickenOnYT** [comment]
mk ty

**Comment by irhrhd** [comment]
Good now more are going down

**Comment by irhrhd** [comment]
All the errors are gone now

**Comment by ChickenOnYT** [comment]
ik i just dismissed all the code errors as "wont fix" because they're not errors just tiny formatting things i've ever seen anyone do

**Comment by ChickenOnYT** [comment]
![image](https://user-images.githubusercontent.com/61570792/111507189-9f2d5080-8707-11eb-92ab-4aa2e1290a26.png)
my solution to slack breaking btw

**Comment by irhrhd** [comment]
Okay what php are we using 5.6 or 7.3

**Comment by irhrhd** [comment]
The whole banner is broken

**Comment by ChickenOnYT** [comment]
> Okay what php are we using 5.6 or 7.3

its 7.4 i think

**Comment by irhrhd** [comment]
Ah  okay because there’s an error checker and on 5.6 the code is fine but on 7.3 it’s bad

**Comment by irhrhd** [comment]
And 7.4 is good so wtf is up with the banner

**Comment by irhrhd** [comment]
All right ill talk to u in a bit then

**Comment by ChickenOnYT** [comment]
back

**Comment by irhrhd** [comment]
Hey thanks for trying to find a way for discord to work

**Comment by irhrhd** [comment]
There is one way I know about

**Comment by irhrhd** [comment]
You have my email address so I can tell you privately

**Comment by ChickenOnYT** [comment]
mk

**Comment by ChickenOnYT** [comment]
updated

**Comment by ChickenOnYT** [comment]
i fixed the cards on /team by making the text the same length i'll figure out a better solution some day

**Comment by irhrhd** [comment]
Okay I’m working on a fix for the frikin banner that’s broken af

**Comment by ChickenOnYT** [comment]
mk

**Comment by irhrhd** [comment]
Okay so what is the theme color I’m just gonna change the purple for now then work on the banner

**Comment by ChickenOnYT** [comment]
make the theme color #009688 because its better than the redpurple thing thats on it

**Comment by irhrhd** [comment]
Okay so can I turn on github pages so we can see the stuff that we change before we change the website

**Comment by ChickenOnYT** [comment]
> Okay so can you turn on github pages so we can see the stuff that we change before we change the website

github pages doesnt do php

**Comment by irhrhd** [comment]
Ah ok

**Comment by irhrhd** [comment]
How do you want /contact to look like

**Comment by ChickenOnYT** [comment]
not sure i'll design it soon

**Comment by irhrhd** [comment]
mk

**Comment by irhrhd** [comment]
I have an idea for it use google forms to have them submit their email then their message.

**Comment by ChickenOnYT** [comment]
okay do that 

just copy the sub to email page and change the title and cannocial url thing to the correct url then i'll create a google form for it soon

**Comment by irhrhd** [comment]
Okay hey think we can change the color of the 404 to #cccccc in the background and have the cloud stay so its not as bright

**Comment by ChickenOnYT** [comment]
ok feel free

**Comment by irhrhd** [comment]
Check The private repo

**Comment by ChickenOnYT** [comment]
mk

**Comment by irhrhd** [comment]
https://colorlib.com/wp/free-404-error-page-templates/ Look through those tell me which one you like the best

**Comment by irhrhd** [comment]
Hmm i still need to fix the banner

**Comment by irhrhd** [comment]
Okay so on the team i might me able to add pictures on everyones thing there is a white rectangle that i could probably change to be a picture

**Comment by ChickenOnYT** [comment]
> https://colorlib.com/wp/free-404-error-page-templates/ Look through those tell me which one you like the best

i used colorlib thats where the 404 page came from and its pretty bad

**Comment by irhrhd** [comment]
Yeah i think some of the others look just a smidge better they are all kinda bad

**Comment by irhrhd** [comment]
How did you get it on i had to download it and now i cant do anything with it

**Comment by irhrhd** [comment]
{
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}

body {
  padding: 0;
  margin: 0;
}

#notfound {
  position: relative;
  height: 100vh;
  background-color: #222;
}

#notfound .notfound {
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound {
  max-width: 460px;
  width: 100%;
  text-align: center;
  line-height: 1.4;
}

.notfound .notfound-404 {
  height: 158px;
  line-height: 153px;
}

.notfound .notfound-404 h1 {
  font-family: 'Josefin Sans', sans-serif;
  color: #222;
  font-size: 220px;
  letter-spacing: 10px;
  margin: 0px;
  font-weight: 700;
  text-shadow: 2px 2px 0px #c9c9c9, -2px -2px 0px #c9c9c9;
}

.notfound .notfound-404 h1>span {
  text-shadow: 2px 2px 0px #ffab00, -2px -2px 0px #ffab00, 0px 0px 8px #ff8700;
}

.notfound p {
  font-family: 'Josefin Sans', sans-serif;
  color: #c9c9c9;
  font-size: 16px;
  font-weight: 400;
  margin-top: 0px;
  margin-bottom: 15px;
}

.notfound a {
  font-family: 'Josefin Sans', sans-serif;
  font-size: 14px;
  text-decoration: none;
  text-transform: uppercase;
  background: transparent;
  color: #c9c9c9;
  border: 2px solid #c9c9c9;
  display: inline-block;
  padding: 10px 25px;
  font-weight: 700;
  -webkit-transition: 0.2s all;
  transition: 0.2s all;
}

.notfound a:hover {
  color: #ffab00;
  border-color: #ffab00;
}

@media only screen and (max-width: 480px) {
  .notfound .notfound-404 {
    height: 122px;
    line-height: 122px;
  }

  .notfound .notfound-404 h1 {
      font-size: 122px;
  }
}
Thats the css style i got

**Comment by irhrhd** [comment]
Okay so on the team i might me able to add pictures on everyones thing there is a white rectangle that i could probably change to be a picture so what do you think?

**Comment by ChickenOnYT** [comment]
> Okay so on the team i might me able to add pictures on everyones thing there is a white rectangle that i could probably change to be a picture so what do you think?

ok we'll add pictures soon but i gtg in like 20 minutes

**Comment by irhrhd** [comment]
When you make my new discord account dont verify the email i will do it cause ill change it to mine

**Comment by ChickenOnYT** [comment]
> When you make my new discord account dont verify the email i will do it cause ill change it to mine

mk

**Comment by irhrhd** [comment]
When will u be back

**Comment by ChickenOnYT** [comment]
also the banner loads for me what happens for you

**Comment by irhrhd** [comment]
Nope it doesn’t because ibb co is blocked so thats why its not loading for
me so itll load for everyone else i assume

**Comment by irhrhd** [comment]
Hey @ChickenOnYT

**Comment by ChickenOnYT** [comment]
> Nope it doesn’t because ibb co is blocked so thats why its not loading for me so itll load for everyone else i assume

rip

**Comment by ChickenOnYT** [comment]
> Hey @ChickenOnYT

yes? also i gtg in like 27 mins turns out

**Comment by irhrhd** [comment]
I know that ull get mad but can u do the discord? Also i can make it so
everyone has an image on the /#team

**Comment by ChickenOnYT** [comment]
ok do that but dont do any copyrighted images or images you dont know  if they're copyrighted

alr i'll make your discord

**Comment by irhrhd** [comment]
Okay just make everyone send a picture they want thats not COPYRIGHTED ©

**Comment by ChickenOnYT** [comment]
ok

**Comment by irhrhd** [comment]
Whats ur name and tag?

**Comment by ChickenOnYT** [comment]
ChickenOnYT#8295

**Comment by irhrhd** [comment]
Says you aren’t accepting requests and you unfriend my old account and friend my new one
RAS#6693

**Comment by ChickenOnYT** [comment]
mk

**Comment by irhrhd** [comment]
Check private

**Comment by irhrhd** [comment]
Confirmation •RAS•

**Comment by ChickenOnYT** [comment]
mk ty

**Comment by ChickenOnYT** [comment]
hi gm

**Comment by ChickenOnYT** [comment]
i dont wanna do colorlib, because they want you to link to them in the footer of their 404 pages

**Comment by irhrhd** [comment]
Yeah okay we’ll find out something different

**Comment by irhrhd** [comment]
Check discord

**Comment by irhrhd** [comment]
Can we add https://wiki.jumpbound.com/wiki/Main_Page as a navigation button

**Comment by ChickenOnYT** [comment]
yeah i made "jumpbound" link to it

**Comment by ChickenOnYT** [comment]
alright can you make the other error pages and add them into the htaccess, then we'll be done

**Comment by ChickenOnYT** [comment]
ugh the htaccess is missing from this repo so i'll add it myself

**Comment by ChickenOnYT** [comment]
also check your @digitalteal.com email i gave you access to the digitalteal.com website directly

**Comment by irhrhd** [comment]
Mk

**Comment by irhrhd** [comment]
Im confirming its me RASBeRrY

**Comment by ChickenOnYT** [comment]
mk

**Comment by ChickenOnYT** [comment]
i just ate ebay

**Comment by ChickenOnYT** [comment]
it was crunchy

**Comment by ChickenOnYT** [comment]
@irhrhd can you make the other error pages lol

**Comment by ChickenOnYT** [comment]
once you make them, add them to .htaccess so they appear. to do that just copy the 404 code in htaccess then change "404" to whatever the new error pages are called

**Comment by irhrhd** [comment]
Yeah i can make it

**Comment by irhrhd** [comment]
Like 502 and stuff like those errors

**Comment by irhrhd** [comment]
Look i can do this if youd like $status = $_SERVER['REDIRECT_STATUS'];
$codes = array( 403 => array('403 Forbidden', 'The server has refused to
fulfill your request.'), 404 => array('404 Not Found', 'The document/file
requested was not found on this server.'), 405 => array('405 Method Not
Allowed', 'The method specified in the Request-Line is not allowed for the
specified resource.'), 408 => array('408 Request Timeout', 'Your browser
failed to send a request in the time allowed by the server.'), 500 =>
array('500
Internal Server Error', 'The request was unsuccessful due to an unexpected
condition encountered by the server.'), 502 => array('502 Bad Gateway', 'The
server received an invalid response from the upstream server while trying
to fulfill the request.'), 504 => array('504 Gateway Timeout', 'The
upstream server failed to send a request in the time allowed by the server.'
), ); $title = $codes[$status][0]; $message = $codes[$status][1]; if ($title
== false || strlen($status) != 3) { $message = 'Please supply a valid
status code.'; } // Insert headers here echo '<h1>'.$title.'</h1> <p>
'.$message.'</p>'; // Insert footer here

**Comment by irhrhd** [comment]
I mean the numbers

**Comment by ChickenOnYT** [comment]
we're supposed to have error pages that look cool for each thing like
there's a 404 page but there should also be other error pages

>

**Comment by ChickenOnYT** [comment]
also http://chng.it/K9gPTPhjgS

**Comment by ChickenOnYT** [comment]
@irhrhd can you make the page background white then make the header sorta a lighter aqua color, and finish the error pages

also be more active on slack

**Comment by irhrhd** [comment]
Im busy doing school and yes illl do that when i can sorry

**Comment by ChickenOnYT** [comment]
mk

**Comment by ChickenOnYT** [comment]
did you ever do the error pages

**Comment by ConnorAhern** [comment]
the digitalteal site is dead and this is no longer open source
